### ISSUE TITLE
Recentre graph on node on click

### ISSUE THREAD

**Issue by seant1** [cousinmango/big-brain-map#29] opened 2020-12-15 09:53 UTC
Allow nodes to be clicked to recenter them on screen.

**Comment by slimlime** [comment] 2020-12-15 09:56
CUCUMBER
 
GIVEN NODE 
WHEN CLICKED
THEN RECENTRE LAYOUT
🥒

**Comment by slimlime** [comment] 2021-01-08 18:59
This was intended to be auto-closed in either the smart commit message or when it was finally merged to main branch.

**Closed by slimlime** 2021-01-08 18:59 UTC
Labels: enhancement
